name: caculadora_de_notas_iesb_v2
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4



  cupertino_icons: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  fonts:
    - family: PatuaOne
      fonts:
        - asset: fonts/PatuaOne-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "icon/icone_calculadora.png"